version: "3.9"

services:
  mariadb:
    image: "mariadb:11.4"
    ports:
      - "33060:3306"
    environment:
      - "MYSQL_DATABASE=diary"
      - "MYSQL_ROOT_PASSWORD=test"
      - "TZ=UTC"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker-volume/mariadb/var/lib/mysql:/var/lib/mysql
      - ./docker-volume/mariadb/var/log/maria:/var/log/maria

  redis:
    image: "redis:7"
    ports:
      - "63790:6379"
    command: redis-server --requirepass "test"
    volumes:
      - ./docker-volume/redis/data:/data
