spring:
  profiles:
    default: dev
    group:
      dev:
        - dev
      prod:
        - prod

  application:
    name: GATEWAY-DISCOVERY-SERVICE

  threads:
    virtual:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
