spring:
  profiles:
    default: dev
    group:
      dev:
        - dev
      prod:
        - prod

  application:
    name: PING-SERVICE

  threads:
    virtual:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
